branches:
  except:
    - master

language: node_js
node_js:
- node
pre_install:
- ulimit -n 8192
install:
- echo "Building for tests"
- yarn run build:test
script:
- echo "Starting tests"
- yarn run test
after_success:
- echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
env:
