branches:
  except:
  - master
language: node_js
node_js:
- node
pre_install:
- ulimit -n 8192
install:
- echo "Building for tests"
- yarn run build:test
script:
- echo "Starting tests"
- yarn run test
after_success:
- echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
env:
  global:
  - secure: GomNrUy9GuccBlXEBBxIRlFtHf1f+qCZLqi/B4SM2Lb8PF8bx2fF4zrFAToLokqsLG+Bz7F4CQwKTVtcy7i7o1W0aW3xp6tOLSxb5Wh/8UvqL9YBMigOaU1Arjvhvht4x5pXjiRsJXdAl6w9c2M1tAGWrfqNsWhE6KTNtPW8w4IIIpV90LnYgqNWVfpHIJGSLx6kgOP/vEJwwdMYbtu5s+rmyH2OYjf7lH+Xg8p9qi4SP6DcfDexerLPgJ8kzp+CVc02IWCtb0IZlapKVz8gTjXpSStj2ZbKkDB3zR6fV4BdbbkRE4at4JbV0x7G1yKzpeHht/BjzWxEz6LW1c7lYEjhTvDi+AmxHW9BTiMylkyX1OZ9FeomtYL8bEmd6sp53xmd2F0U2kNqqInoz705IpgkbQimI5Bp+mxsOEXCJtwhGgCtE9XhkeapwrPLdXIbcCNMaikV7cLR8ALypdyLyPKrfV6j9N+EveMBGUUzOWlDtq9D7twckjiAZCbrFzfVLhldEgsZX/3g1wlMh+LdJvAK7Gabceccj41xp3xeGkaIe2h2SN3yCRCjgl/z1Auzi+9FqsZ0mtA3Wxm5EDcYo+38htIOSAmI0+uTb1BF7DzZUf7FvqqjFwCzPWkxNP20WqRgo/2SK+zYkT5caKg/1/c1uXeewYdwGzCHJssVuqU=
  - secure: FFJ6pTXOIeiiBgWTPnX7CKVqmG5mApEUSKaTTVx/svhurwNlzPgWNBqXUjEXoXi2qdREIeXHgi3t1++MONAF7ecAlw2AAE2gg5XjV+I5bN0Mv8gEKiPac4gauAKCFxmNr3sqx9XGgXPFQBvaoGwtpA/Rl4iay0HaHU+3d+X4bw5UUuj03LeUVhcWr7BGqwmAcfkUYw8PGGzbWhjeNbjaxWMUNn/UgAbQFDJMEZrNODhYNbYJvT6Z91FwpwRs8buTwU5nldUEtdhEGPdYRtjz+vPizd3xOH+G+/GEy9R+vrI9jn0PnnCqGdNLwt0T6sGKToRqw2G5RMMineLaw1+IIbvGoC6WN/qjhIeA/UM8ZDrYv+m93o7hV627BSkFYNnPdCpKDoBDPCKBZUznrPZRFkz4kxRU2+P87kUAFALfS3MNnY4RpnUt0McozJCfgLSX76LP0DVY2r2qLs5TaY8RG0dbZRCP8ce+e/1M9voTq23ScP9ejuDLBxnKDfaXbuuFOEhxoXRgNEqxh0TgcRWWXm7+R5/zQEul0fM+KMMtiF+opHNnuG1lkM6+JT/W5zdOrsgKnyqrzWCwtaF2T8In47+xNlxkn0td74xttd/cJC4kBwaw9Rx2MySj2XYhRqyEJhcF5njFsSPNlbYwOxJI+T53T6e35idwkFlrxzT3ivk=
