branches:
  except:
  - master
language: node_js
node_js:
- node
pre_install:
- ulimit -n 8192
install:
- echo "Building for tests"
- yarn run build:test
script:
- echo "Starting tests"
- yarn run test
after_success:
- echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
env:
  global:
  - secure: cm+GB/TJZLEBx9bD6yNGtV/qhvLXIpX1s+LmFYCCnZqqSioX6fKVCKCdx8kTb0lvL4glAQ0Yq+4BhT45B2y1pmIbnljMWx7l3LRMHIsS2BTOTtLkx3S2E9i8bLFaxuupfkcQyCkzGOTGVdPkZayOzTgqoYDoFeLkmLFOEPkgCVwhGO9u5Std7RdsMMfR/BfYEm950AbsXqLHCd7PAHDa6WB5ait7eqh3E6iJbaU1JNPVhGoNks7TiEPvXDIXG9Ei/lFuS3oH9wJ2Ldqt8ZyVYZgl2GsrIbFxY3XJxcayXJFw8h27yzYKmbOhKpEKq5QWIxzGD8vp11yg1zzFeij3UQErWUxa7cI7M1DtJyaJaLP1cnulqtxmB9GXkFhBJqhsQz0Wf+6wTwMjdn8/DXJPCFsxCtQvHf1PLpGLqoA/KrVJqpnIcchfl3otJNNQhFqraRKxn/CKX5jJdCqQuwIoXp980LLma/3Y8g/OF6gnMJ/yt7OBtp6UdDdyq6ipzJx/7E3Od16n5RIlVFnKIhcS70euimMBRkKGOalBGDHrhhqBNm4m8eaV+jxnBPqbUljq6PvjOopTfBUtJS9n5ng3soypZqPBWb7h+SXNGX659+XWzZ+kTztiNqEYkAtyrUw7B5XHM5GTp9n3YCaw2E0z4dG6jw6FMnHGeSgrOAZANwE=
  - secure: mFj2b+rrRWUeV/jvKtZ98iBA+AL1j6lfLehikoGDz8rdqNlkqhK9SfmHlckyT/Z+jlqSRw9ARB7s2z5MexD32vtzAzHcxjEa1e4R2Ke9wILwWNiFBhsmf9c+gI3hbKRnrkbIPPk0hMV6c5P7fbqv2vDvPgL35UFmIp5VeN0F7bQydOhHJTnkcNY7YiL02eh1go50GZPTKrCEB8iqMS5A9y4VD1L3d+TV/ZIxM2L+DrzBLI+nbs2hZBF+UVqD6Zlm/ieMVtL1PVIYu0ERBiNGOoId/7GRPtFOuaB+CxZ7MjrgCaUpDO/PcpdWA+Myix1emzO7T3Ihv08UQt4kXIMxIYFJr8sV3yjwDnxyknwMm+4nrfOarPY2NURjUKh1SSTuK81WylNzLujT7/WJukCiL6b5lmUgVxfHuIJqlL2gEK4+l5HdtTj3/uI8K/EAWcncyx/mOUz4tgQHnTwGwO6UbtVKWuY3iUD6zkLGXA1cqeOyTIhtklpjxzAbgJKWcoMVVxYtNT1X3TGHJqoQK59k0F/6Sa6OAAy0XbHyk3/UG278XMDEGnkQ/5fgvzi0GCMKFmOpqQrtCapm9JUq6y+kskbVqCf2biW4NM/qop9lTyldJJ6M66jFn861y78Vpvcv5pczzsOwyR4cGXjBqhwcYvxKeQHVICY7wQKn6tQI+os=
